### ISSUE TITLE
Runs perfectly but wont connect to open ai 

### ISSUE THREAD

**Issue by ac1dburnz** [ecasanova/openai-slackbot#1]
I ran everything and it seems to work. I have it running and I Auth with no problem .After i try and talk on the slack channel I don’t get any responses and i looked at the openai page and there has not been a connection to the api key

**Comment by ecasanova** [comment]
Hello! @colinborins 

You can check the permissions of the slack app, that it has enough permission to listen and write to your channel, and that the bot is inside the channel

The bot only responds to direct mentions.

**Comment by ac1dburnz** [comment]
ya i did check that and it does.

**Comment by ac1dburnz** [comment]
I ended up figuring it out
